- name: genegate intm key
  openssl_privatekey:
    path: "{{ intm_key_path }}"
    passphrase: "{{ kpass }}"
    cipher: aes256

- name: generate intm csr
  openssl_csr:
    path: "{{ intm_csr_path }}"
    privatekey_path: "{{ intm_key_path }}"
    country_name: BY
    organization_name: epam
    email_address: "kanstantsin_shchura@epam.com"
    common_name: "{{ common_name }}"
    state_or_province_name: belarus
    privatekey_passphrase: "{{ kpass }}"

- stat:
    path: "{{ intm_cert_path }}"
  register: sym

- name: create intm cert
  openssl_certificate:
    path: "{{ intm_cert_path }}"
    privatekey_path: "{{ root_key_path }}"
 #   privatekey_path: "{{ intm_key_path }}"
    csr_path:  "{{ intm_csr_path }}"
    provider: selfsigned
    privatekey_passphrase: "{{ kpass }}"
    issuer:
      C: BE
      0: epam
      CN: local CA
#    selfsigned_not_after: "2012312359Z"
#    selfsigned_not_before: "1011112359Z"

  
