- name: cert
  connection: local
  hosts: localhost
  vars:
    kpass: "{{ lookup ('file', '/root/ansible/pass.txt') }}"
  tasks:
  - name: renegate key
    openssl_privatekey:
      path: /root/ansible/private/example.key.pem
      passphrase: "{{ kpass }}"
      cipher: aes256

  - name: renerate example.com csr
    openssl_csr:
      path: /root/ansible/example.com.csr
      privatekey_path: /root/ansible/private/example.key.pem
      country_name: BY
      organization_name: epam
      common_name: example.com
      state_or_province_name: belarus
      privatekey_passphrase: "{{ kpass }}"

  - name: create example.com cert
    openssl_certificate:
      path: /root/ansible/example.com.cert
      privatekey_path: /root/ansible/private/example.key.pem
      csr_path: /root/ansible/example.com.csr
      provider: selfsigned
      privatekey_passphrase: "{{ kpass }}"

  - name: create csr customer.example.com
    openssl_csr:
      path: /root/ansible/customer.example.com.csr
      privatekey_path: /root/ansible/private/example.key.pem
      country_name: BY
      organization_name: epam
      common_name: customer.example.com
      state_or_province_name: belarus
      privatekey_passphrase: "{{ kpass }}"

  - name: create customer.example.com cert
    openssl_certificate:
      path: /root/ansible/customer.example.com.cert
      privatekey_path: /root/ansible/private/example.key.pem
      csr_path: /root/ansible/customer.example.com.csr
      provider: selfsigned
      privatekey_passphrase: "{{ kpass }}"

  - name: "create csr *.datastore.example.com"
    openssl_csr:
      path: /root/ansible/*.datastore.example.com.csr
      privatekey_path: /root/ansible/private/example.key.pem
      country_name: BY
      organization_name: epam
      common_name: "*.datastore.example.com"
      state_or_province_name: belarus
      privatekey_passphrase: "{{ kpass }}"
  
  - name: "create cert *.datastore.example.com"
    openssl_certificate:
      path: /root/ansible/*.datastore.example.com.cert
      privatekey_path: /root/ansible/private/example.key.pem
      csr_path: /root/ansible/*.datastore.example.com.csr
      provider: selfsigned
      privatekey_passphrase: "{{ kpass }}"

