- name: cert
  connection: local
  hosts: localhost
  vars:
#    domain: "www.example.com"
#    com_name: "local CA"
    countryName: "BY"
    stateOrProvinceName: "VA"
    localityName: "minsk"
    organizationName: "epam"
    commonName: "www.example.com"
    alt_name: "www.example.com"
    nginx_conf_folder: "nginx_conf"
    docker_container_name: "nginx-https"
    
    domain_certs: 
    - www.example.com
    - www.customer.example.com
    - "*.datastore.example.com"
    art_folder: "artifacts"
  vars_prompt:
  - name: "root_kpass"
    prompt: "input password for private key"

  roles:
  - role: generate_root_cert
    artifacts_f: "{{ art_folder }}"
    kpass: "{{ root_kpass }}"
    common_name: "{{ commonName }}"
    root_key_path: "./{{ art_folder }}/ca.key"
    root_cert_path: "./{{ art_folder }}/ca.crt"
    C: "{{ countryName }}"
    ST: "{{ stateOrProvinceName }}"
    L: "{{ localityName }}"
    O: "{{ organizationName }}"
    CN: "{{ commonName }}"
    alt: "{{ alt_name }}"

  - role: sign_domain_cert
    artifacts_f: "{{ art_folder }}"
    kpass: "{{ root_kpass }}"
    domain_names: "{{ domain_certs }}"
    root_key_path: "./{{ art_folder }}/ca.key"
    root_cert_path: "./{{ art_folder }}/ca.crt"

  - role: nginx_docker
    domain_names: "{{ domain_certs }}"
    nginx_folder: "{{ nginx_conf_folder }}"
    docker_name: "{{ docker_container_name }}"
    alt: "{{ alt_name }}"
