- name: genegate domain key
  openssl_privatekey:
    path: "./{{ artifacts_f }}/{{ item }}.pass.key"
    passphrase: "{{ kpass }}"
    cipher: aes256
  with_items: "{{ domain_names }}"

- name: unencrypt server private key
  shell: test -e "./{{ artifacts_f }}/{{ item }}.key"  ||  openssl rsa -passin "pass:{{ kpass }}" -in "./{{ artifacts_f }}/{{ item }}.pass.key" -out "./{{ artifacts_f }}/{{ item }}.key"
  with_items: "{{ domain_names }}"
  ignore_errors: yes

- name: generate domain csr
  openssl_csr:
    path: "./{{ artifacts_f }}/{{ item }}.csr"
    privatekey_path: "./{{ artifacts_f }}/{{ item }}.key"
    country_name: "BY"
    organization_name: epam
    common_name: "{{ item }}"
    email_address: "kanstantsin_shchura@epam.com"
    state_or_province_name: minsk
    privatekey_passphrase: "{{ kpass }}"
  with_items: "{{ domain_names }}"

- name: copy extfile for openssl
  template:
    src: server.cnf
    dest: "./{{ item }}.cnf"
  with_items: "{{ domain_names }}"

- name: generate server crt
  command:  openssl x509 -req -in "./{{ artifacts_f }}/{{ item }}.csr" -CA "{{ root_cert_path }}" -CAkey "{{ root_key_path }}" -CAcreateserial -out "./{{ artifacts_f }}/{{ item }}.crt"  -sha256 -passin pass:"{{ kpass }}" -extfile  "{{ item }}.cnf"
  with_items: "{{ domain_names }}"
