- name: create folder for arifacts
  file: 
    path: "{{ artifacts_f }}"
    state: directory

- name: renegate root key
  openssl_privatekey:
    path: "{{ root_key_path }}"
    passphrase: "{{ kpass }}"
    cipher: aes256
    state: present

- name: create openssl config file ca.cnf
  template:
   src: ca.cnf
   dest: ./ca.cnf

- name: generate root CA
  command: openssl req -x509 -new -nodes -key "{{ root_key_path }}"  -sha256 -days 1024 -out  "{{ root_cert_path }}" -config ca.cnf  -passin pass:"{{ kpass }}"
